environment: DEPLOYMENT_ENV
NODE_ENV: NODE_ENV

node:
  port: PORT
  baseUrl: BASE_URL

session:
  secret: SESSION_SECRET

tests:
  functional:
    waitForTimeout: FUNCTIONAL_WAIT_FOR_TIMEOUT_VALUE
    waitForAction: FUNCTIONAL_WAIT_FOR_ACTION_VALUE
    outputDir: FUNCTIONAL_OUTPUT_DIR
    url: TEST_URL
    proxy: FUNCTIONAL_IDAM_PROXY
    proxyByPass: FUNCTIONAL_IDAM_SERVER
    verifyDonePageOnCrossbrowser: VERIFY_DONE_PAGE_CROSSBROWSER
    idam:
      idamTestUsername: FUNCTIONAL_IDAM_USERNAME
      idamTestPassword: FUNCTIONAL_IDAM_PASSWORD
      idamTestForename: IDAM_TEST_FORENAME
      idamTestSurname: IDAM_TEST_SURNAME
      idamTestUserGroup: IDAM_TEST_USER_GROUP
      idamTestLevelOfAccess: IDAM_TEST_LEVEL_OF_ACCESS
      idamTestSupportCreateAccountEndpoint: IDAM_TEST_SUPPORT_CREATE_ACCOUNT_ENDPOINT

saucelabs:
  waitForTimeout: SAUCELABS_WAIT_FOR_TIMEOUT_VALUE
  smartWait: SAUCELABS_SMART_WAIT_VALUE

ssl:
  hpkp:
    maxAge: HPKP_MAX_AGE
    sha256s: HPKP_SHAS

services:
  redis:
    url: REDISCLOUD_URL
    useSSL: USE_SSL
    encryptionAtRestKey: REDIS_ENCRYPTION_SECRET
  idam:
    apiHealth: IDAM_APP_HEALHCHECK_URL
    authenticationHealth: IDAM_AUTHENTICATION_HEALHCHECK_URL
    apiUrl: IDAM_API_URL
    secret: IDAM_SECRET
    loginUrl: IDAM_LOGIN_URL
    clientId: IDAM_CLIENT_ID
    proxy: IDAM_PROXY
  googleAnalytics:
    id: GOOGLE_ANALYTICS_ID
    trackingUrl: GOOGLE_ANALYTICS_TRACKING_URL
  applicationInsights:
    instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY
  evidenceManagementClient:
    url: EVIDENCE_MANAGEMENT_CLIENT_API_URL
    health: EVIDENCE_MANAGEMENT_CLIENT_API_HEALTHCHECK_URL
    uploadEndpoint: EVIDENCE_MANAGEMENT_CLIENT_API_UPLOAD_ENDPOINT
    downloadEndpoint: EVIDENCE_MANAGEMENT_CLIENT_API_DOWNLOAD_ENDPOINT
  rateLimiter:
    total: RATE_LIMITER_TOTAL
    expire: RATE_LIMITER_EXPIRE
    enabled: RATE_LIMITER_ENABLED
  orchestrationService:
    baseUrl: ORCHESTRATION_SERVICE_URL
    getCaseUrl: ORCHESTRATION_SERVICE_GET_PETITION_URL
    getAosCaseUrl: ORCHESTRATION_SERVICE_GET_AOS_PETITION_URL
    submitCaseUrl: ORCHESTRATION_SERVICE_POST_PETITION_URL
    health: ORCHESTRATION_SERVICE_HEALTH_URL
    draftEndpoint: ORCHESTRATION_SERVICE_DRAFT_ENDPOINT
  petitionerFrontend:
    url: PETITIONER_FRONTEND_URL
  rfeFrontend:
    url: RESPONDENT_FRONTEND_URL
  dnFrontend:
    url: DECREE_NISI_FRONTEND_URL
  caseMaintenance:
    baseUrl: CASE_MAINTENANCE_BASE_URL
  feesAndPayments:
    url: FEES_AND_PAYMENTS_URL
    health: FEES_AND_PAYMENTS_HEALTHCHECK_URL
  antennaWebchat:
    url: ANTENNA_WEBCHAT_URL
    service: ANTENNA_WEBCHAT_SERVICE
    version: ANTENNA_WEBCHAT_VERSION

journey:
  timeoutDelay: JOURNEY_TIMEOUT_DELAY

features:
  idam: FEATURE_IDAM
  antennaWebchat: FEATURE_ANTENNA_WEBCHAT
  antennaWebchatUserAttribute: FEATURE_ANTENNA_WEBCHAT_USER_ATTRIBUTE
  dynatrace: FEATURE_DYNATRACE
  pingRedis: FEATURE_PING_REDIS

ccd:
  courts: CCD_DIGITAL_COURTS
