apiVersion: v2
description: Divorce - Decree Absolute
name: div-da
version: 2.0.26
dependencies:
  - name: nodejs
    version: 3.1.1
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: redis
    version: 17.7.2
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      -  pr
  - name: idam-pr
    version: 2.2.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    tags:
      - idam-pr
